use_frameworks!

target 'UIKevent_Example' do
  pod 'UIKevent', :path => '../'


  target 'UIKevent_Tests' do
      inherit! :search_paths

pod 'Quick'
pod 'Nimble'
pod 'FBSnapshotTestCase'
pod 'Nimble-Snapshots'
  end
end
