use_frameworks!

target 'UIKevent_Example' do
  pod 'UIKevent', :path => '../'

  target 'UIKevent_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
